export interface Problem {
  code: string; // e.g., 'A', 'B', 'C'
  id: string; // e.g., 'CHEFSUM'
  title: string;
  difficulty: 'Easy' | 'Medium-Easy' | 'Medium' | 'Medium-Hard' | 'Hard';
  maxPoints: number;
}

export interface Participant {
  name: string;
  institution: string;
  solvedProblems: string[]; // List of problem codes solved
  problemAttempts: { [problemCode: string]: { attempts: number; solvedTime: number | null } }; // track attempts and solving time
  penaltyTime: number; // in minutes
  solvedCount: number;
  rank: number;
  status: 'Active' | 'Inactive' | 'Disqualified';
}

export interface Submission {
  id: string;
  participantName: string;
  problemCode: string;
  problemName: string;
  timestamp: number; // minutes from start of contest (0 to 180)
  verdict: 'Pending' | 'Running' | 'Accepted' | 'Wrong Answer' | 'Time Limit Exceeded' | 'Runtime Error';
  language: 'C++' | 'Java' | 'Python' | 'Go';
  executionTime: number; // in seconds, e.g., 0.12
  codeChecksum?: string;
}

export interface ContestActivity {
  id: string;
  type: 'JOIN' | 'SUBMIT' | 'REJUDGE' | 'FREEZE' | 'UNFREEZE';
  description: string;
  timestamp: number; // date timestamp or minutes from start
  contestMinutes?: number;
}

export const PROBLEMS: Problem[] = [
  { code: 'A', id: 'CHEFSUM', title: 'Chef and Sum', difficulty: 'Easy', maxPoints: 100 },
  { code: 'B', id: 'TREEDIST', title: 'Tree Distance', difficulty: 'Medium-Easy', maxPoints: 100 },
  { code: 'C', id: 'SORTALGO', title: 'Efficient Sorting', difficulty: 'Medium', maxPoints: 100 },
  { code: 'D', id: 'MAXPATH', title: 'Max Path Queries', difficulty: 'Medium-Hard', maxPoints: 100 },
  { code: 'E', id: 'GRIDGAME', title: 'Grid Game Theory', difficulty: 'Hard', maxPoints: 100 },
  { code: 'F', id: 'STRPALIN', title: 'String Palindromes', difficulty: 'Hard', maxPoints: 100 },
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    name: 'Tanishq Gupta',
    institution: 'VIT Vellore',
    solvedProblems: ['A', 'B'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 12 },
      'B': { attempts: 2, solvedTime: 45 },
      'C': { attempts: 1, solvedTime: null },
    },
    penaltyTime: 77, // 12 + 45 + (1 WA on B * 20) = 77
    solvedCount: 2,
    rank: 1,
    status: 'Active',
  },
  {
    name: 'Aditya Sen',
    institution: 'IIT Bombay',
    solvedProblems: ['A', 'C'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 15 },
      'B': { attempts: 3, solvedTime: null },
      'C': { attempts: 1, solvedTime: 65 },
    },
    penaltyTime: 80, // 15 + 65 = 80
    solvedCount: 2,
    rank: 2,
    status: 'Active',
  },
  {
    name: 'Sarah Connor',
    institution: 'BITS Pilani',
    solvedProblems: ['A'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 8 },
      'B': { attempts: 1, solvedTime: null },
    },
    penaltyTime: 8,
    solvedCount: 1,
    rank: 3,
    status: 'Active',
  },
  {
    name: 'Kenji Sato',
    institution: 'University of Tokyo',
    solvedProblems: ['A', 'B', 'D'],
    problemAttempts: {
      'A': { attempts: 2, solvedTime: 22 }, // 22 + 20 = 42
      'B': { attempts: 1, solvedTime: 50 }, // 50
      'D': { attempts: 3, solvedTime: 110 }, // 110 + 40 = 150
    },
    penaltyTime: 242, // 42 + 50 + 150 = 242
    solvedCount: 3,
    rank: 4,
    status: 'Active',
  },
  {
    name: 'Emma Watson',
    institution: 'Oxford University',
    solvedProblems: ['A', 'B'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 30 },
      'B': { attempts: 1, solvedTime: 55 },
    },
    penaltyTime: 85,
    solvedCount: 2,
    rank: 5,
    status: 'Active',
  },
  {
    name: 'Li Wei',
    institution: 'Tsinghua University',
    solvedProblems: ['A', 'C', 'E'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 5 },
      'C': { attempts: 2, solvedTime: 40 }, // 40 + 20 = 60
      'E': { attempts: 4, solvedTime: 135 }, // 135 + 60 = 195
    },
    penaltyTime: 260,
    solvedCount: 3,
    rank: 6,
    status: 'Active',
  },
  {
    name: 'Rahul Sharma',
    institution: 'Delhi Technological University',
    solvedProblems: [],
    problemAttempts: {
      'A': { attempts: 2, solvedTime: null },
    },
    penaltyTime: 0,
    solvedCount: 0,
    rank: 7,
    status: 'Active',
  },
  {
    name: 'Elena Rostova',
    institution: 'Moscow State University',
    solvedProblems: ['A', 'B', 'C', 'D'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 10 },
      'B': { attempts: 1, solvedTime: 35 },
      'C': { attempts: 1, solvedTime: 72 },
      'D': { attempts: 2, solvedTime: 125 }, // 125 + 20 = 145
    },
    penaltyTime: 262,
    solvedCount: 4,
    rank: 8,
    status: 'Active',
  },
  {
    name: 'Carlos Santana',
    institution: 'Unam Mexico',
    solvedProblems: ['B'],
    problemAttempts: {
      'A': { attempts: 2, solvedTime: null },
      'B': { attempts: 1, solvedTime: 92 },
    },
    penaltyTime: 92,
    solvedCount: 1,
    rank: 9,
    status: 'Active',
  },
  {
    name: 'Aisha Yusuf',
    institution: 'University of Cape Town',
    solvedProblems: ['A', 'B'],
    problemAttempts: {
      'A': { attempts: 3, solvedTime: 48 }, // 48 + 40 = 88
      'B': { attempts: 1, solvedTime: 82 }, // 82
    },
    penaltyTime: 170,
    solvedCount: 2,
    rank: 10,
    status: 'Active',
  },
  {
    name: 'David Miller',
    institution: 'MIT',
    solvedProblems: ['A', 'C'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 18 },
      'C': { attempts: 3, solvedTime: 95 }, // 95 + 40 = 135
    },
    penaltyTime: 153,
    solvedCount: 2,
    rank: 11,
    status: 'Inactive',
  },
  {
    name: 'Sofia Rodriguez',
    institution: 'University of São Paulo',
    solvedProblems: ['A'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 40 },
    },
    penaltyTime: 40,
    solvedCount: 1,
    rank: 12,
    status: 'Active',
  },
  {
    name: 'Nikolai Volkov',
    institution: 'SPbSU ITMO',
    solvedProblems: ['A', 'B', 'C', 'D', 'E'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 4 },
      'B': { attempts: 1, solvedTime: 18 },
      'C': { attempts: 1, solvedTime: 32 },
      'D': { attempts: 1, solvedTime: 55 },
      'E': { attempts: 2, solvedTime: 98 }, // 98 + 20 = 118
      'F': { attempts: 3, solvedTime: null },
    },
    penaltyTime: 227, // 4+18+32+55+118 = 227
    solvedCount: 5,
    rank: 13,
    status: 'Active',
  },
  {
    name: 'Rohan Gupta',
    institution: 'VIT Vellore',
    solvedProblems: ['A'],
    problemAttempts: {
      'A': { attempts: 2, solvedTime: 58 }, // 58 + 20 = 78
    },
    penaltyTime: 78,
    solvedCount: 1,
    rank: 14,
    status: 'Active',
  },
  {
    name: 'Alice Cooper',
    institution: 'Stanford University',
    solvedProblems: ['A', 'B', 'C'],
    problemAttempts: {
      'A': { attempts: 1, solvedTime: 10 },
      'B': { attempts: 2, solvedTime: 38 }, // 38 + 20 = 58
      'C': { attempts: 1, solvedTime: 70 },
    },
    penaltyTime: 138,
    solvedCount: 3,
    rank: 15,
    status: 'Active',
  }
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    id: 'sub_1',
    participantName: 'Nikolai Volkov',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 4,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.02,
  },
  {
    id: 'sub_2',
    participantName: 'Li Wei',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 5,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.01,
  },
  {
    id: 'sub_3',
    participantName: 'Sarah Connor',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 8,
    verdict: 'Accepted',
    language: 'Python',
    executionTime: 0.12,
  },
  {
    id: 'sub_4',
    participantName: 'Alice Cooper',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 10,
    verdict: 'Accepted',
    language: 'Java',
    executionTime: 0.28,
  },
  {
    id: 'sub_5',
    participantName: 'Elena Rostova',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 10,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.03,
  },
  {
    id: 'sub_6',
    participantName: 'Tanishq Gupta',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 12,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.02,
  },
  {
    id: 'sub_7',
    participantName: 'Aditya Sen',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 15,
    verdict: 'Accepted',
    language: 'Python',
    executionTime: 0.08,
  },
  {
    id: 'sub_8',
    participantName: 'David Miller',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 18,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.04,
  },
  {
    id: 'sub_9',
    participantName: 'Nikolai Volkov',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 18,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.06,
  },
  {
    id: 'sub_10',
    participantName: 'Kenji Sato',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 19,
    verdict: 'Wrong Answer',
    language: 'Go',
    executionTime: 0.05,
  },
  {
    id: 'sub_11',
    participantName: 'Kenji Sato',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 22,
    verdict: 'Accepted',
    language: 'Go',
    executionTime: 0.04,
  },
  {
    id: 'sub_12',
    participantName: 'Emma Watson',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 30,
    verdict: 'Accepted',
    language: 'Java',
    executionTime: 0.15,
  },
  {
    id: 'sub_13',
    participantName: 'Nikolai Volkov',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 32,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.08,
  },
  {
    id: 'sub_14',
    participantName: 'Elena Rostova',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 35,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.05,
  },
  {
    id: 'sub_15',
    participantName: 'Alice Cooper',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 35,
    verdict: 'Time Limit Exceeded',
    language: 'Java',
    executionTime: 2.01,
  },
  {
    id: 'sub_16',
    participantName: 'Alice Cooper',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 38,
    verdict: 'Accepted',
    language: 'Java',
    executionTime: 0.45,
  },
  {
    id: 'sub_17',
    participantName: 'Sofia Rodriguez',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 40,
    verdict: 'Accepted',
    language: 'Python',
    executionTime: 0.18,
  },
  {
    id: 'sub_18',
    participantName: 'Li Wei',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 40,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.06,
  },
  {
    id: 'sub_19',
    participantName: 'Li Wei',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 40,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.05,
  },
  {
    id: 'sub_20',
    participantName: 'Tanishq Gupta',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 42,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.04,
  },
  {
    id: 'sub_21',
    participantName: 'Tanishq Gupta',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 45,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.03,
  },
  {
    id: 'sub_22',
    participantName: 'Aisha Yusuf',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 45,
    verdict: 'Wrong Answer',
    language: 'Python',
    executionTime: 0.12,
  },
  {
    id: 'sub_23',
    participantName: 'Aisha Yusuf',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 46,
    verdict: 'Runtime Error',
    language: 'Python',
    executionTime: 0.11,
  },
  {
    id: 'sub_24',
    participantName: 'Aisha Yusuf',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 48,
    verdict: 'Accepted',
    language: 'Python',
    executionTime: 0.10,
  },
  {
    id: 'sub_25',
    participantName: 'Kenji Sato',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 50,
    verdict: 'Accepted',
    language: 'Go',
    executionTime: 0.08,
  },
  {
    id: 'sub_26',
    participantName: 'Nikolai Volkov',
    problemCode: 'D',
    problemName: 'Max Path Queries',
    timestamp: 55,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.11,
  },
  {
    id: 'sub_27',
    participantName: 'Emma Watson',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 55,
    verdict: 'Accepted',
    language: 'Java',
    executionTime: 0.22,
  },
  {
    id: 'sub_28',
    participantName: 'Rohan Gupta',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 56,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.03,
  },
  {
    id: 'sub_29',
    participantName: 'Rohan Gupta',
    problemCode: 'A',
    problemName: 'Chef and Sum',
    timestamp: 58,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.02,
  },
  {
    id: 'sub_30',
    participantName: 'Aditya Sen',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 65,
    verdict: 'Accepted',
    language: 'Python',
    executionTime: 0.14,
  },
  {
    id: 'sub_31',
    participantName: 'Alice Cooper',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 70,
    verdict: 'Accepted',
    language: 'Java',
    executionTime: 0.35,
  },
  {
    id: 'sub_32',
    participantName: 'Elena Rostova',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 72,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.08,
  },
  {
    id: 'sub_33',
    participantName: 'Aisha Yusuf',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 82,
    verdict: 'Accepted',
    language: 'Python',
    executionTime: 0.15,
  },
  {
    id: 'sub_34',
    participantName: 'Carlos Santana',
    problemCode: 'B',
    problemName: 'Tree Distance',
    timestamp: 92,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.07,
  },
  {
    id: 'sub_35',
    participantName: 'David Miller',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 92,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.09,
  },
  {
    id: 'sub_36',
    participantName: 'David Miller',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 94,
    verdict: 'Time Limit Exceeded',
    language: 'C++',
    executionTime: 2.05,
  },
  {
    id: 'sub_37',
    participantName: 'David Miller',
    problemCode: 'C',
    problemName: 'Efficient Sorting',
    timestamp: 95,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.07,
  },
  {
    id: 'sub_38',
    participantName: 'Nikolai Volkov',
    problemCode: 'E',
    problemName: 'Grid Game Theory',
    timestamp: 98,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.15,
  },
  {
    id: 'sub_39',
    participantName: 'Nikolai Volkov',
    problemCode: 'E',
    problemName: 'Grid Game Theory',
    timestamp: 98,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.14,
  },
  {
    id: 'sub_40',
    participantName: 'Kenji Sato',
    problemCode: 'D',
    problemName: 'Max Path Queries',
    timestamp: 102,
    verdict: 'Wrong Answer',
    language: 'Go',
    executionTime: 0.09,
  },
  {
    id: 'sub_41',
    participantName: 'Kenji Sato',
    problemCode: 'D',
    problemName: 'Max Path Queries',
    timestamp: 105,
    verdict: 'Wrong Answer',
    language: 'Go',
    executionTime: 0.08,
  },
  {
    id: 'sub_42',
    participantName: 'Kenji Sato',
    problemCode: 'D',
    problemName: 'Max Path Queries',
    timestamp: 110,
    verdict: 'Accepted',
    language: 'Go',
    executionTime: 0.07,
  },
  {
    id: 'sub_43',
    participantName: 'Elena Rostova',
    problemCode: 'D',
    problemName: 'Max Path Queries',
    timestamp: 120,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.12,
  },
  {
    id: 'sub_44',
    participantName: 'Elena Rostova',
    problemCode: 'D',
    problemName: 'Max Path Queries',
    timestamp: 125,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.11,
  },
  {
    id: 'sub_45',
    participantName: 'Li Wei',
    problemCode: 'E',
    problemName: 'Grid Game Theory',
    timestamp: 130,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.21,
  },
  {
    id: 'sub_46',
    participantName: 'Li Wei',
    problemCode: 'E',
    problemName: 'Grid Game Theory',
    timestamp: 131,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.18,
  },
  {
    id: 'sub_47',
    participantName: 'Li Wei',
    problemCode: 'E',
    problemName: 'Grid Game Theory',
    timestamp: 132,
    verdict: 'Wrong Answer',
    language: 'C++',
    executionTime: 0.20,
  },
  {
    id: 'sub_48',
    participantName: 'Li Wei',
    problemCode: 'E',
    problemName: 'Grid Game Theory',
    timestamp: 135,
    verdict: 'Accepted',
    language: 'C++',
    executionTime: 0.18,
  }
];

export const INITIAL_ACTIVITIES: ContestActivity[] = [
  { id: 'act_1', type: 'JOIN', description: 'Nikolai Volkov joined the contest', timestamp: Date.now() - 3600000 * 2.5 },
  { id: 'act_2', type: 'JOIN', description: 'Tanishq Gupta joined the contest', timestamp: Date.now() - 3600000 * 2.4 },
  { id: 'act_3', type: 'SUBMIT', description: 'Nikolai Volkov solved Chef and Sum [Problem A]', timestamp: Date.now() - 3600000 * 2.4 + 240000 },
  { id: 'act_4', type: 'SUBMIT', description: 'Li Wei solved Chef and Sum [Problem A]', timestamp: Date.now() - 3600000 * 2.4 + 300000 },
  { id: 'act_5', type: 'SUBMIT', description: 'Tanishq Gupta solved Chef and Sum [Problem A]', timestamp: Date.now() - 3600000 * 2.4 + 720000 },
  { id: 'act_6', type: 'SUBMIT', description: 'Nikolai Volkov solved Tree Distance [Problem B]', timestamp: Date.now() - 3600000 * 2.4 + 1080000 },
  { id: 'act_7', type: 'SUBMIT', description: 'Nikolai Volkov solved Efficient Sorting [Problem C]', timestamp: Date.now() - 3600000 * 2.4 + 1920000 },
  { id: 'act_8', type: 'SUBMIT', description: 'Tanishq Gupta solved Tree Distance [Problem B]', timestamp: Date.now() - 3600000 * 2.4 + 2700000 },
  { id: 'act_9', type: 'SUBMIT', description: 'Nikolai Volkov solved Max Path Queries [Problem D]', timestamp: Date.now() - 3600000 * 2.4 + 3300000 },
  { id: 'act_10', type: 'SUBMIT', description: 'Nikolai Volkov solved Grid Game Theory [Problem E]', timestamp: Date.now() - 3600000 * 2.4 + 5880000 },
];
